export const storeKeys = {
  PREFLIGHT_TIME_DURATION: 'PREFLIGHT_TIME_DURATION',
  MOVE_TIME_DURATION: 'MOVE_TIME_DURATION',
  DEFAULT_HEIGHT_TOLERANCE_THRESHOLD: 'DEFAULT_HEIGHT_TOLERANCE_THRESHOLD',
  DESK_OFFSET_HEIGHT: 'DESK_OFFSET_HEIGHT',
  RAW_MIN_HEIGHT: 'RAW_MIN_HEIGHT',
  RAW_MAX_HEIGHT: 'RAW_MAX_HEIGHT'
};
